name: call_recorder
description: "Personal call recording app for Android"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  intl: ^0.19.0
  just_audio: ^0.9.40
  sqflite: ^2.4.1
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
